### ISSUE TITLE
CPU temperature shown truncated

### ISSUE THREAD

**Issue by vadimgrn** [MerlinRdev/bluecave-merlin#13]
General/Tools, Temperatures
2.4 GHz: 84°C  -  5 GHz: 81°C  -  CPU: **10°C**

**Comment by paldier** [comment]
It means 100+, too hot, you need to keep your router cool
I will fix it

**Comment by chongaik3** [comment]
Firmware 5.1.0
2.4 GHz: 84°C - 5 GHz: 81°C - CPU: 100°C
With USB Fan
2.4 GHz: 54°C - 5 GHz: 56°C - CPU: 78°C

Did not use 5.1.1 because issue with IPTV unable resolve, no Adaptive QoS and devices connected to Guest Network not visible under Network Map.

But thanks for @paldier effort.

**Comment by paldier** [comment]
> 
> 
> Firmware 5.1.0
> 2.4 GHz: 84°C - 5 GHz: 81°C - CPU: 100°C
> With USB Fan
> 2.4 GHz: 54°C - 5 GHz: 56°C - CPU: 78°C
> 
> Did not use 5.1.1 because issue with IPTV unable resolve, no Adaptive QoS and devices connected to Guest Network not visible under Network Map.
> 
> But thanks for @paldier effort.

It's problem of the asus,i can't do anything
